import './globals.css'
import { Inter } from 'next/font/google'
import Hydrate from './components/Hydrate'
import Nav from './components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='mx-10 md:mx-32'>
        <Hydrate>
        <Nav/>
        {children}
        </Hydrate>
        </body>
    </html>
  )
}
