import './globals.css'
import { Inter } from 'next/font/google'
import Hydrate from './components/Hydrate'
import Nav from './components/Nav'
import { Roboto, Lobster_Two } from 'next/font/google'

const roboto = Roboto({weight:["400", "500", "700"], subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`mx-32 ${roboto.className}`}>
        <Hydrate>
        <Nav />
        {children}
        </Hydrate>
        </body>
    </html>
  )
}
